# Generated by Django 5.1.2 on 2024-10-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'permissions': [('visualizar_lista', 'Puede visualizar la lista de vehiculos')]},
        ),
    ]
